### ISSUE TITLE
Preset weather

### ISSUE THREAD

**Issue by mholzi** [mholzi/dashview#111]
Of course. Here are the full, detailed code changes to resolve the duplicate weather entity issue and to update the default entity to `weather.forecast_home`.

The solution involves two main parts:
1.  **Fixing your configuration file:** This is the root cause of the entity appearing twice.
2.  **Updating the code:** This will change the default fallback entity as you requested.

---

### Part 1: Fix Your Configuration File

First, you must fix the structure of your configuration. This is the most important step.

1.  **Open the file:** `custom_components/dashview/www/config/house_setup.json`
2.  **The Problem:** The key `"weather_entity"` exists in two places.
3.  **The Fix:** Remove the `weather_entity` key from *inside* the `house_config` object.

**Your file should be changed FROM this structure:**
```json
{
    "house_config": {
        "weather_entity": "weather.home",  // <-- DELETE THIS LINE
        "rooms": {
            ...
        },
        "floors": {
            ...
        }
    },
    "weather_entity": "weather.home"
}
```

**TO this correct structure:**
```json
{
    "house_config": {
        "rooms": {
            ...
        },
        "floors": {
            ...
        }
    },
    "weather_entity": "weather.home" // <-- Keep only this top-level one
}
```
*After saving this change, you may need to use the "Re-Import from house_setup.json" button in the admin panel to apply it to your live configuration.*

---

### Part 2: Full Code Changes for Default Entity

Here are the complete code modifications for each file that needs to be updated to use `weather.forecast_home` as the default.

#### **File: `custom_components/dashview/store.py`**
This change updates the default value on the backend if no weather entity is configured in storage.

```python
# full code for this function
def get_weather_entity(self, default="weather.forecast_home"):
    """Get the configured weather entity."""
    # Note: weather.home is a placeholder, adjust if needed
    return self._data.get("weather_entity", default)
```

#### **File: `custom_components/dashview/services.yaml`**
This updates the example shown in the Home Assistant services UI.

```yaml
# full code for this service definition
set_weather_entity:
  name: Set Weather Entity
  description: Sets the primary weather entity for the DashView panel.
  fields:
    entity_id:
      name: Entity ID
      description: The entity_id of the weather provider (e.g., weather.forecast_home).
      required: true
      example: "weather.forecast_home"
      selector:
        entity:
          domain: weather
```

#### **File: `custom_components/dashview/www/dashview-panel.js`**
This change updates the fallback entity used by the frontend if the configuration can't be loaded from the backend.

```javascript
// full code for this function
_getCurrentWeatherEntityId() {
    // No longer reads from a sensor, just returns the stored property
    return this._weatherEntityId || 'weather.forecast_home'; // Fallback for safety
}
```

### Final Steps to Apply Changes

1.  **Save all modified files.**
2.  **Restart Home Assistant:** This is necessary for the changes in the Python files (`store.py`) and `services.yaml` to take effect.
3.  **Clear Browser Cache:** After restarting, clear your browser's cache completely (e.g., via `Ctrl+F5` or `Cmd+Shift+R`) to ensure it downloads the updated `dashview-panel.js` file.
