### ISSUE TITLE
Config summary

### ISSUE THREAD

**Issue by mholzi** [mholzi/dashview#129]
Of course. Here is a detailed walkthrough, including the code modifications required, to add a "Configuration Summary" section to the bottom of the DashView admin panel.

This new section will automatically count and display the number of floors, rooms, and various types of entities (like motion sensors and media players) that are currently configured in your `house_config`.

### Step 1: Add the Summary Section to the Admin UI

First, we need to create a placeholder in the admin panel where the summary will be displayed.

**File to Edit:** `custom_components/dashview/www/admin.html`

**Action:** Open this file and add the following HTML code block at the very bottom, just before the closing `</div>` of the `tabs-container`.

```html
<div class="config-section">
        <h5>Configuration Summary</h5>
        <div id="config-summary-container" class="summary-grid">
            <p>Load a configuration tab to view summary.</p>
        </div>
    </div>

</div> ```

### Step 2: Implement the Logic to Calculate and Display the Summary

Next, we'll add the JavaScript code that reads the configuration, counts the items, and injects the results into the HTML section we just created.

**File to Edit:** `custom_components/dashview/www/dashview-panel.js`

**Action:** Open this file and add the new `_updateAdminSummary` method to the `DashviewPanel` class. Then, we will call this new method from the existing functions that load the admin configuration.

1.  **Add the `_updateAdminSummary` method:**

    ```javascript
    // In custom_components/dashview/www/dashview-panel.js
    // Add this entire new method inside the DashviewPanel class.
    // A good place is after the deleteRoom() method.

    _updateAdminSummary() {
        const shadow = this.shadowRoot;
        if (!shadow) return;

        const container = shadow.getElementById('config-summary-container');
        const houseConfig = this._adminLocalState.houseConfig;

        if (!container || !houseConfig) {
            if (container) container.innerHTML = '<p>Could not load configuration summary.</p>';
            return;
        }

        const floors = houseConfig.floors || {};
        const rooms = houseConfig.rooms || {};

        const stats = {
            Floors: Object.keys(floors).length,
            Rooms: Object.keys(rooms).length,
        };

        const entityCounts = {};

        // Initialize counters for known entity types
        const knownEntityTypes = [
            'motion', 'window', 'smoke', 'vibration', 'music', 'tv',
            'dishwasher', 'washing', 'dryer', 'freezer', 'mower',
            'lights', 'covers', 'media_players'
        ];
        knownEntityTypes.forEach(type => entityCounts[type] = 0);

        Object.values(rooms).forEach(room => {
            if (room.lights) entityCounts.lights += room.lights.length;
            if (room.covers) entityCounts.covers += room.covers.length;
            if (room.media_players) entityCounts.media_players += room.media_players.length;

            if (room.header_entities) {
                room.header_entities.forEach(entity => {
                    if (entityCounts.hasOwnProperty(entity.entity_type)) {
                        entityCounts[entity.entity_type]++;
                    }
                });
            }
        });

        let summaryHTML = '';
        Object.entries(stats).forEach(([name, count]) => {
             summaryHTML += `<div class="summary-item"><strong>${name}:</strong><span>${count}</span></div>`;
        });

        Object.entries(entityCounts).forEach(([type, count]) => {
            if (count > 0) {
                const name = type.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase());
                summaryHTML += `<div class="summary-item"><strong>${name}:</strong><span>${count}</span></div>`;
            }
        });

        if (summaryHTML === '') {
            container.innerHTML = '<p>No items found in configuration.</p>';
        } else {
            container.innerHTML = summaryHTML;
        }
    }
    ```

2.  **Call the new method from existing functions:**
    Now, find the `loadAdminConfiguration` and `loadFloorMaintenance` methods and add a call to `this._updateAdminSummary();` within them. This ensures the summary is updated whenever configuration data is loaded in the admin panel.

    ```javascript
    // In custom_components/dashview/www/dashview-panel.js

    // Find the loadAdminConfiguration method and add the call at the end of the `try` block
    async loadAdminConfiguration() {
        // ... (existing code)
        try {
            // ... (existing code to load config)
            this._setStatusMessage(statusElement, '✓ House configuration loaded successfully', 'success');
            this._updateAdminSummary(); // <-- ADD THIS LINE
            return;
        } catch (error) {
            this._setStatusMessage(statusElement, `✗ Error loading configuration: ${error.message}`, 'error');
            console.error('[DashView] Error loading admin configuration:', error);
            return;
        }
        // ... (rest of the function)
    }

    // Find the loadFloorMaintenance method and add the call at the end of the `try` block
    async loadFloorMaintenance() {
        // ... (existing code)
        try {
            // ... (existing code to load config)
            this._renderFloorsList();
            this._setStatusMessage(statusElement, '✓ Floor configuration loaded successfully', 'success');
            this._updateAdminSummary(); // <-- ADD THIS LINE
            console.log('[DashView] Floor maintenance loaded successfully');
        } catch (error) {
            // ... (existing code)
        }
    }
    ```

### Step 3: Add CSS for a Clean Look

Finally, let's add some styles to make the summary section look organized and clean.

**File to Edit:** `custom_components/dashview/www/style.css`

**Action:** Open this file and add the following CSS code at the end.

```css
/* In custom_components/dashview/www/style.css */

/* Add these styles at the end of the file */
.summary-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
    gap: 12px;
    padding-top: 10px;
}

.summary-item {
    background-color: var(--gray000);
    border-radius: 8px;
    padding: 12px;
    display: flex;
    justify-content: space-between;
    align-items: center;
    font-size: 0.9em;
    border: 1px solid var(--gray200);
}

.summary-item strong {
    color: var(--primary-text-color);
    font-weight: 500;
}

.summary-item span {
    font-weight: 700;
    font-size: 1.1em;
    color: var(--primary-color);
    background-color: var(--gray100);
    padding: 2px 8px;
    border-radius: 12px;
}
```

After completing these steps, when you navigate to the Admin panel in DashView and load a configuration tab, the new summary section will appear at the bottom and display the counts of your configured items.
