### ISSUE TITLE
Media popup

### ISSUE THREAD

**Issue by mholzi** [mholzi/dashview#186]
Of course. To achieve the desired tabbed layout for the music popup, you'll need to modify the structure, styling, and script within a single file: `custom_components/dashview/www/music.html`.

Here are the specific code snippets that need to change.

#### 1. HTML Structure

First, remove the old header that contains the "Musik" title and icon.

**Remove this entire block:**
```html
<div class="music-title">
    <i class="mdi mdi-music"></i>
    <span>Musik</span>
</div>
```
The containing `<div class="music-tab-header">` will now only hold the new room tabs.

---

#### 2. CSS Styling

Next, replace the old CSS for the icon-based "chips" with new styles for the text-based tabs.

**Replace this CSS block:**
```css
.music-tab-header {
    display: grid;
    grid-template-columns: min-content 1fr;
    align-items: center;
    gap: 20px;
    margin-bottom: 20px;
    padding-bottom: 15px;
    border-bottom: 1px solid rgba(255, 255, 255, 0.1);
}

.music-title {
    display: flex;
    align-items: center;
    gap: 12px;
    font-size: 16px;
    font-weight: 500;
    color: var(--gray1000);
    white-space: nowrap;
}

.music-title i {
    font-size: 20px;
    color: var(--gray1000);
}

.music-room-tabs {
    display: flex;
    gap: 8px;
    justify-content: flex-end;
    flex-wrap: wrap;
}

.music-tab-chip {
    padding: 13px;
    border-radius: 50%;
    border: none;
    cursor: pointer;
    display: flex;
    align-items: center;
    justify-content: center;
    transition: all 0.2s ease;
    background: var(--gray800);
    color: var(--gray000);
}

.music-tab-chip.active {
    background: var(--active-big);
    color: var(--gray000);
}

.music-tab-chip i {
    width: 22px;
    height: 22px;
    font-size: 22px;
}
```

**With this new CSS block:**
```css
.music-tab-header {
    margin-bottom: 20px;
    padding-bottom: 15px;
    border-bottom: 1px solid rgba(255, 255, 255, 0.1);
}

/* NEW: Styles for text-based room tabs, inspired by the weather card */
.music-room-tabs {
    display: flex;
    gap: 8px;
    flex-wrap: wrap; /* Allow tabs to wrap on smaller screens */
}

.music-tab-button {
    padding: 8px 16px;
    background-color: var(--gray100);
    border: none;
    border-radius: 16px;
    cursor: pointer;
    font-size: 0.9em;
    font-family: var(--primary-font-family);
    color: var(--secondary-text-color);
    transition: all 0.2s ease;
}

.music-tab-button.active {
    background: var(--active-big);
    color: var(--gray000);
    font-weight: 500;
}
```

---

#### 3. JavaScript Logic

Finally, update the inline `<script>` to generate text-based buttons instead of icon chips and ensure it uses the room's friendly name.

**In the `loadMusicRoomsFromConfig` function, modify the `musicRooms.push` call:**
```javascript
// CHANGE THIS:
musicRooms.push({
    id: roomId,
    name: roomConfig.name || roomId,
    icon: roomConfig.icon || 'mdi-music',
    mediaPlayers: roomConfig.media_players
});

// TO THIS:
musicRooms.push({
    id: roomId,
    name: roomConfig.friendly_name || roomConfig.name || roomId, // Use friendly_name
    mediaPlayers: roomConfig.media_players
});
```

**In the `updateTabsForConfiguration` function, modify the loop that creates the tabs:**
```javascript
// CHANGE THIS:
const currentTabs = Array.from(tabContainer.querySelectorAll('.music-tab-chip')).map(t => t.dataset.roomId);
// ...
musicRooms.forEach((room, index) => {
    // Create tab chip
    const tabChip = document.createElement('button');
    tabChip.className = `music-tab-chip ${index === 0 ? 'active' : ''}`;
    tabChip.dataset.roomId = room.id;
    tabChip.title = room.name;
    tabChip.innerHTML = `<i class="${room.icon}"></i>`;
    tabContainer.appendChild(tabChip);
    // ...
});

// TO THIS:
const currentTabs = Array.from(tabContainer.querySelectorAll('.music-tab-button')).map(t => t.dataset.roomId);
// ...
musicRooms.forEach((room, index) => {
    // MODIFIED: Create a text-based tab button
    const tabButton = document.createElement('button');
    tabButton.className = `music-tab-button ${index === 0 ? 'active' : ''}`;
    tabButton.dataset.roomId = room.id;
    tabButton.textContent = room.name; // Set text to friendly name
    tabContainer.appendChild(tabButton);
    // ...
});
```

**In the `setupTabSwitching` function, update the selector:**
```javascript
// CHANGE THIS:
const tabChips = document.querySelectorAll('.music-tab-chip');

// TO THIS:
const tabButtons = document.querySelectorAll('.music-tab-button');
```
... and then replace all further instances of `tabChips` with `tabButtons` within that function.

These changes will transform the music popup to use the clean, text-based tab navigation you requested.
