### ISSUE TITLE
Entity Details Popup: Styling and Integration

### ISSUE THREAD

**Issue by mholzi** [mholzi/dashview#292]
## Overview
Finalize the Entity Detail Overlay Popup feature with comprehensive styling, visual polish, and full integration into the DashView ecosystem. This enhancement ensures the popup system feels native to DashView's design language while providing excellent user experience across all devices and use cases.

## User Story
As a user, I want the entity detail popups to feel seamlessly integrated into DashView with beautiful styling, smooth animations, and intuitive interactions that enhance rather than disrupt my dashboard experience.

#### Popup Container Styling
- **Backdrop Effects**: Sophisticated blur and overlay effects consistent with DashView themes
- **Container Design**: Rounded corners, shadows, and spacing matching existing cards
- **Responsive Layout**: Adaptive sizing for mobile, tablet, and desktop viewports
- **Theme Integration**: Full support for light/dark mode with CSS custom properties

#### Content Area Styling
- **Template Adaptation**: Ensure all reused templates look natural in popup context
- **Spacing Consistency**: Maintain DashView's spacing patterns and visual hierarchy
- **Interactive Elements**: Style buttons, controls, and inputs to match existing patterns
- **Loading States**: Elegant skeleton screens and loading indicators

#### Entry/Exit Animations
```css
/* Popup entry animation */
.entity-detail-popup {
  animation: popup-enter 300ms cubic-bezier(0.4, 0.0, 0.2, 1);
  transform-origin: center center;
}

@keyframes popup-enter {
  0% {
    opacity: 0;
    transform: scale(0.8) translateY(20px);
  }
  100% {
    opacity: 1;
    transform: scale(1) translateY(0);
  }
}
```

#### Content Loading Animations
- **Skeleton Screens**: Animated placeholders during content loading
- **Fade Transitions**: Smooth content appearance once loaded
- **Error States**: Gentle animations for error/retry states

#### Performance Optimizations
- **GPU Acceleration**: Use `transform` and `opacity` for 60fps animations
- **Reduced Motion**: Respect `prefers-reduced-motion` user preferences
- **Animation Throttling**: Optimize for lower-end devices

#### Breakpoint Strategy
```css
/* Mobile: Full-screen popup */
@media (max-width: 767px) {
  .entity-detail-popup {
    width: 100vw;
    height: 100vh;
    border-radius: 0;
    animation: popup-slide-up 300ms ease-out;
  }
}

/* Tablet: Centered with margins */
@media (min-width: 768px) and (max-width: 1023px) {
  .entity-detail-popup {
    width: 90vw;
    max-width: 600px;
    max-height: 80vh;
  }
}

/* Desktop: Optimal sizing */
@media (min-width: 1024px) {
  .entity-detail-popup {
    width: 800px;
    max-height: 85vh;
  }
}
```

#### Touch-Friendly Design
- **Larger Touch Targets**: 44px minimum touch target size
- **Swipe Gestures**: Optional swipe-to-close functionality
- **Edge Cases**: Handle safe areas on notched devices

#### Gesture Integration
```javascript
// Connect with gesture detection system
const gestureDetector = new GestureDetector({
  longTapDuration: 500,
  enableVisualFeedback: true
});

// Apply to all sensor cards
this._attachGestureListeners();
```

#### Accessibility Features
- **ARIA Labels**: Comprehensive screen reader support
- **Keyboard Navigation**: Full keyboard accessibility
- **Focus Management**: Proper focus trapping within popup
- **Color Contrast**: WCAG AA compliance for all text and UI elements

#### Performance Integration
- **Lazy Loading**: Load popup assets only when needed
- **Memory Management**: Efficient cleanup and garbage collection
- **Bundle Optimization**: Minimize impact on initial page load

#### Smart Positioning
```javascript
// Intelligent popup positioning based on trigger element
_calculateOptimalPosition(triggerElement) {
  const viewport = this._getViewportDimensions();
  const triggerRect = triggerElement.getBoundingClientRect();
  
  // Position popup to avoid covering trigger element
  // Account for screen edges and optimal viewing angles
}
```

#### Context Preservation  
- **Background Dimming**: Subtle background blur without losing context
- **Animation Continuity**: Smooth transition from card to popup
- **State Preservation**: Maintain dashboard state during popup interaction

#### Progressive Enhancement
- **Core Functionality**: Works without animations on older browsers
- **Enhanced Experience**: Full feature set on modern browsers
- **Graceful Degradation**: Fallbacks for unsupported features

#### Custom Properties Integration
```css
:host {
  /* Popup-specific custom properties */
  --popup-backdrop-blur: 12px;
  --popup-backdrop-opacity: 0.4;
  --popup-border-radius: var(--ha-card-border-radius);
  --popup-shadow: 0 20px 40px rgba(0,0,0,0.15);
  --popup-animation-duration: 300ms;
  --popup-animation-easing: cubic-bezier(0.4, 0.0, 0.2, 1);
}

/* Dark mode overrides */
@media (prefers-color-scheme: dark) {
  :host {
    --popup-backdrop-opacity: 0.6;
    --popup-shadow: 0 20px 40px rgba(0,0,0,0.3);
  }
}
```

#### Component Isolation
- **Shadow DOM**: Maintain style isolation within popup
- **CSS Scoping**: Prevent style leakage to/from main dashboard
- **Variable Inheritance**: Proper CSS custom property cascading

#### Visual Testing
- **Screenshot Testing**: Automated visual regression testing
- **Cross-Browser**: Chrome, Firefox, Safari, Edge compatibility
- **Device Testing**: iOS Safari, Android Chrome, various screen sizes

#### Performance Testing
- **Animation Performance**: 60fps animation benchmarking
- **Memory Usage**: Leak detection and optimization
- **Load Time Impact**: Measure bundle size increase

#### User Experience Testing
- **Usability**: A/B testing with actual users
- **Accessibility**: Screen reader and keyboard testing
- **Edge Cases**: Unusual screen sizes and orientations

### Files to Create/Modify
- `custom_components/dashview/www/style.css` (enhance with popup styles)
- `custom_components/dashview/www/lib/ui/popup-manager.js` (final integration)
- `custom_components/dashview/www/lib/ui/EntityDetailManager.js` (styling coordination)
- Various template files (minor styling adaptations)

### Integration Checkpoints
1. **Gesture Integration**: Connect all components from previous issues
2. **Style System**: Integrate with existing DashView CSS architecture
3. **Animation System**: Implement smooth, performant animations
4. **Accessibility**: Ensure full accessibility compliance
5. **Performance**: Optimize for production deployment

## Acceptance Criteria
- [ ] Complete visual design matching DashView's aesthetic
- [ ] Smooth 60fps animations on all supported devices
- [ ] Full responsive design working across all screen sizes
- [ ] Complete accessibility compliance (WCAG AA)
- [ ] Performance impact minimal (<5% bundle size increase)
- [ ] Cross-browser compatibility verified
- [ ] Integration with gesture detection seamless
- [ ] Template styling adaptations complete
- [ ] Error states and edge cases handled gracefully
- [ ] Documentation complete for future maintenance

## Testing Requirements
- [ ] Visual regression testing across all templates
- [ ] Performance benchmarking on various devices
- [ ] Accessibility audit with automated and manual testing
- [ ] User acceptance testing with sample user groups
- [ ] Cross-browser compatibility verification
- [ ] Memory leak and performance profiling
- [ ] Animation performance testing at 60fps

## Dependencies
- **Issue #289**: Long-Tap Gesture Detection Infrastructure
- **Issue #290**: Generic Popup Container System  
- **Issue #291**: Entity Content Orchestration Manager
- Existing DashView style system and theme architecture

## Implementation Notes
- Maintain strict consistency with existing DashView design language
- Use CSS Grid and Flexbox for robust layout systems
- Implement comprehensive error boundaries for graceful failure
- Consider future extensibility for additional entity types
- Document all new CSS custom properties and their usage
- Follow DashView's existing animation and interaction patterns

## Definition of Done
This issue completes the Entity Detail Overlay Popup feature, making it production-ready and fully integrated into DashView's ecosystem. All four components work together to provide a seamless, beautiful, and accessible user experience.
