### ISSUE TITLE
Various changes

### ISSUE THREAD

**Issue by mholzi** [mholzi/dashview#49]
**Formatting of the popup cards:**

To mirror the provided "bubble-card" layout and styling for your DashView popups and outer cards, you'll need to modify your `style.css` file. The changes will focus on adjusting spacing, backgrounds, and icon styles to align with your specified parameters.

Here’s a detailed prompt outlining the necessary modifications to your `custom_components/dashview/www/style.css` file:

```css
/* --- Global Layout Adjustments for 8px Horizontal Margin --- */
body, :host {
    /* Existing properties... */
    padding: 12px 8px; /* Changed from 12px to 12px top/bottom and 8px left/right */
    /* Ensure no conflicting margin on .dashboard-container if it has it */
}

/* --- Pop-up Styles mirroring Bubble Card Layout --- */
.popup-content {
    background-color: var(--popupBG); /* Ensure background is set to popupBG */
    margin: 0;
    padding: 20px;
    border-radius: 30px;
    max-width: 600px;
    width: calc(100% - 16px); /* Adjusted from 40px to 16px to achieve 8px left/right margin */
    position: relative;
    transform: translateY(100vh);
    transition: transform 0.4s cubic-bezier(0.25, 0.46, 0.45, 0.94);
}

.popup-header {
    background: var(--popupBG) !important; /* To explicitly mirror bubble-card header background */
    /* Existing properties... */
}

.popup-close {
    background: none; /* To mirror bubble-card header button background */
    /* Existing properties... */
}

.popup-icon {
    background-color: var(--green) !important; /* For the icon container background */
    color: var(--gray800) !important; /* To mirror ha-icon color */
    opacity: 1 !important; /* To mirror ha-icon opacity */
    font-size: 24px !important; /* To mirror bubble-icon size */
    border-radius: 50%; /* Often icons in bubble cards are circular */
    padding: 8px; /* Add some padding around the icon within its background */
}

/* --- Ensure no margin-bottom inside popup content for card-like elements --- */
/* This section aims to emulate the 'ha-card { margin-bottom: 0px !important; }'
   and '--vertical-stack-card-gap: 0px!important;' within the popup. */
.popup-body > .weather-forecast-card,
.popup-body > .hourly-forecast-container,
.popup-body > .daily-forecast-container,
.popup-body > .pollen-card {
    margin-bottom: 0px !important; /* Remove bottom margin for cards directly inside popup body */
    margin-top: 0px !important; /* Also remove top margin if present, for continuous stacking */
}

.popup-body > .hourly-forecast-container h4,
.popup-body > .daily-forecast-container h4 {
    margin-top: 12px; /* Re-add some top margin for section headers if they are now flush */
}

/* Any section within .popup-body that acts like a stacked item should have its internal margin adjusted */
.popup-body .info-section,
.popup-body .train-departures-container .train-departure-card {
    margin-bottom: 0px !important; /* Remove any default bottom margins */
    margin-top: 0px !important;
}

/* Adjust general spacing within popup-body if it now looks too cramped */
.popup-body > div {
    padding-bottom: 12px; /* Add internal padding to sections instead of relying on margin-bottom */
}

/* Ensure no excessive gap if elements are using flex/grid with gap property inside popup-body */
.popup-body {
    display: flex;
    flex-direction: column;
    gap: 0px !important; /* Emulate --vertical-stack-card-gap: 0px!important; */
}


/* --- Existing styles remain unchanged unless specified above --- */
/* ... */
```

**MDI icon loading:**

If you prefer not to self-host the MDI icons and want to leverage Home Assistant's built-in MDI sourcing, the issue likely stems from how the Shadow DOM isolates CSS or a subtle conflict in the loading order. Home Assistant itself loads MDI globally, but your DashView panel, being a custom web component with a Shadow DOM, needs to explicitly ensure it can access those global styles or that they are correctly inherited.

Given that your `dashview-panel.js` already includes logic to inject CSS variables into the Shadow DOM, the most direct solution without self-hosting would be to ensure that the Shadow DOM can properly inherit or utilize the MDI font definition that Home Assistant provides.

Here's a revised approach to modify your `custom_components/dashview/www/style.css` and `custom_components/dashview/www/dashview-panel.js` to potentially resolve this, by ensuring the MDI font family is explicitly applied and recognized within the Shadow DOM:

**1. Modify `custom_components/dashview/www/style.css`:**

Remove the `@import` URL for the MDI font, as Home Assistant already provides it. Instead, focus on defining the core `.mdi` class and ensuring a fallback `font-family` if the main MDI font isn't recognized for some reason.

```css
/* custom_components/dashview/www/style.css */

/* REMOVE THIS LINE: */
/* @import url('https://cdn.jsdelivr.net/npm/@mdi/font@7.4.47/css/materialdesignicons.min.css'); */

/* Add or ensure the following .mdi class definition is present.
   The 'Material Design Icons' font-family is provided by Home Assistant. */
.mdi {
  font-family: 'Material Design Icons', sans-serif !important; /* Ensure this is set and has a generic fallback */
  font-weight: normal;
  font-style: normal;
  font-size: inherit;
  display: inline-block;
  line-height: 1;
  text-transform: none;
  letter-spacing: normal;
  word-wrap: normal;
  white-space: nowrap;
  direction: ltr;
  -webkit-font-smoothing: antialiased;
  text-rendering: optimizeLegibility;
  -moz-osx-font-smoothing: grayscale;
  font-feature-settings: 'liga';
}

/* Ensure any specific icon rules in your CSS also inherit or use .mdi */
/* Example: */
.kiosk-button .icon {
    font-size: 24px;
    color: var(--primary-text-color);
    padding: 4px;
    /* Ensure no conflicting font-family here that might override .mdi */
}

/* ... other existing styles ... */
```

**2. Modify `custom_components/dashview/www/dashview-panel.js`:**

The `_injectCSSVariables` method is responsible for injecting CSS rules into your Shadow DOM. You need to ensure that the core MDI font definition is either inherited from the main document (which it should be by default) or explicitly injected in a way that respects Home Assistant's global MDI setup.

The current `_injectCSSVariables` primarily focuses on custom CSS variables. While `font-family` is usually inherited, sometimes Shadow DOM can be tricky. A common technique for custom elements that rely on global fonts is to apply the font to the `:host` selector or a top-level container within the Shadow DOM.

Let's modify `_injectCSSVariables` to ensure MDI font is available within the Shadow DOM.

```javascript
// custom_components/dashview/www/dashview-panel.js

// ... (existing code) ...

  // Inject CSS variables into Shadow DOM for proper theming support
  _injectCSSVariables(shadow) {
    const cssVariables = document.createElement('style');
    cssVariables.textContent = `
      :host, :root {
        /* Base Font */
        --primary-font-family: 'Space Grotesk', sans-serif;
        /* Ensure MDI font is available throughout the host */
        font-family: var(--primary-font-family), 'Material Design Icons', sans-serif;

        /* Default to light mode variables */
        --background: #f5f7fa;
        --popupBG: #fafbfc;
        --highlight: rgba(40, 40, 42, 0.05);
        --highlight-active: rgba(250, 251, 252, 0.1);
        
        --gray000: #edeff2;
        --gray100: #e9eaec;
        --gray200: #d6d7d9;
        --gray400: #909193;
        --gray500: #707173;
        --gray800: #0f0f10;
        
        --green: #c5e4ac;
        --purple: #e3d4f6;
        --yellow: #faedae;
        --red: #f0a994;
        --blue: #c8ddfa;
        --blue-dark: #abcbf8;
        --orange: #ffd1b1;

        /* Gradients */
        --active-light: linear-gradient(145deg, rgba(255,245,200,1) 0%, rgba(255,225,130,1) 60%, rgba(255,200,90,1) 150%);
        --active-big: linear-gradient(145deg, rgba(255,220,178,1) 0%, rgba(255,176,233,1) 60%, rgba(104,156,255,1) 150%);
        --active-small: linear-gradient(145deg, rgba(255,212,193,1) 0%, rgba(248,177,235,1) 100%);
        
        /* Main Interface Colors */
        --primary-color: var(--blue-dark);
        --accent-color: var(--blue-dark);
        --primary-background-color: var(--background);
        --secondary-background-color: var(--background);
        --divider-color: var(--gray100);

        /* Text */
        --primary-text-color: var(--gray800);
        --secondary-text-color: var(--gray500);
        --text-primary-color: var(--gray800);
        --disabled-text-color: var(--gray400);

        /* Cards */
        --card-background-color: var(--gray000);
        --ha-card-background: var(--gray000);
        --ha-card-border-radius: 30px;
        --ha-card-border-width: 0px;
        --ha-card-box-shadow: none;
      }

      /* Dark Mode Overrides */
      @media (prefers-color-scheme: dark) {
        :host, :root {
          --background: #28282A;
          --popupBG: #28282A;
          --highlight: rgba(250, 251, 252, 0.05);
          --highlight-active: rgba(40, 40, 42, 0.1);
          
          --gray000: #3a3b3d;
          --gray100: #353637;
          --gray200: #404142;
          --gray400: #737476;
          --gray500: #939496;
          --gray800: #ffffff;

          --green: #d2e7d6;
          --purple: #d5c1ed;
          --yellow: #fbf1be;
          --red: #e7625f;
          --blue: #abcbf8;
          --blue-dark: #c8ddfa;
          --orange: #ffba8a;
        }
      }
      /* Explicitly add MDI font-family for elements inside Shadow DOM that might need it */
      .mdi {
        font-family: 'Material Design Icons', sans-serif !important;
      }
    `;
    shadow.appendChild(cssVariables);
  }

// ... (rest of the code) ...
```

**Explanation:**

1.  **Removing `@import` in `style.css`**: Since Home Assistant already loads the MDI font globally, importing it again might cause conflicts or be redundant.
2.  **Explicit `font-family` in `style.css`**: By defining `.mdi { font-family: 'Material Design Icons', sans-serif !important; }` in your main `style.css`, you ensure that any element with the `.mdi` class in the main document correctly requests the MDI font.
3.  **Injecting `font-family` into Shadow DOM via `_injectCSSVariables`**:
    * By adding `font-family: var(--primary-font-family), 'Material Design Icons', sans-serif;` to the `:host, :root` selector within the injected style, you tell the Shadow DOM to prioritize `Space Grotesk`, but also to specifically look for `'Material Design Icons'` if `Space Grotesk` doesn't apply (e.g., for elements with `.mdi` class).
    * Adding a direct `.mdi` rule within the injected style block ensures that the font-family is explicitly provided within the Shadow DOM's scope. This can sometimes be necessary if the default inheritance mechanism doesn't fully propagate the font definition into the isolated Shadow DOM.

After applying these changes, clear your browser cache and refresh Home Assistant. This approach ensures that your DashView panel leverages Home Assistant's existing MDI font definitions while explicitly applying them within its Shadow DOM for correct rendering.
