### ISSUE TITLE
Popup menu

### ISSUE THREAD

**Issue by mholzi** [mholzi/dashview#83]
Of course. You've pointed out a classic CSS positioning problem. The bottom menu bar feels disconnected from the main content because it's positioned relative to the entire browser window, not the content area. This is especially noticeable when the Home Assistant sidebar opens and pushes the main content over.

Here is a detailed prompt to refactor the CSS for the bottom navigation bar. This change will fix the width and alignment issue, making it feel perfectly in sync with the main content container.

---

#### **1. The Goal**

The goal is to modify the CSS for the bottom navigation bar (`.bottom-nav`) so that its width and horizontal position are always perfectly aligned with the main content area (`.dashboard-container`). This will create a more integrated and professional look and feel.

#### **2. The Root Cause**

The current `.bottom-nav` uses `left: 50%`, `transform: translateX(-50%)`, and a calculated `width`. This method centers the bar within the overall browser viewport. It has no awareness of the main content pane, which is why it doesn't move when the Home Assistant sidebar opens and it can appear to have a slightly different width than the content above it.

#### **3. The Solution**

We will change the CSS for the `.bottom-nav` to use a more modern and robust centering technique that ensures its width and `max-width` properties behave identically to the `.dashboard-container`.

This involves a simple change to the `.bottom-nav` rule in `custom_components/dashview/www/style.css`.

**Action:** Replace the existing `.bottom-nav` CSS rule with the corrected version below.

```css
// In custom_components/dashview/www/style.css

/* --- FIND THIS EXISTING RULE --- */
.bottom-nav {
    position: fixed;
    bottom: 10px;
    left: 50%;
    transform: translateX(-50%);
    width: calc(100% - 20px);
    max-width: 500px;
    background-color: var(--gray100);
    border-radius: 100px;
    padding: 10px;
    display: flex;
    justify-content: space-around;
    align-items: center;
    box-shadow: 0 4px 12px rgba(0,0,0,0.1);
    z-index: 5;
}


/* --- REPLACE IT WITH THIS NEW, CORRECTED RULE --- */
.bottom-nav {
    position: fixed;
    bottom: 10px;
    /* The new centering and width mechanism */
    left: 8px;
    right: 8px;
    margin: 0 auto;
    
    /* Set width to 100% and let max-width constrain it, just like the main container */
    width: 100%;
    max-width: 500px; 
    box-sizing: border-box; /* Ensures padding is included in the width calculation */
    
    /* These properties remain the same */
    background-color: var(--gray100);
    border-radius: 100px;
    padding: 10px;
    display: flex;
    justify-content: space-around;
    align-items: center;
    box-shadow: 0 4px 12px rgba(0,0,0,0.1);
    z-index: 5;
}
```

### **How This Fixes the Issues**

* **Perfect Alignment:** By setting `left`, `right`, and `margin: 0 auto`, the navigation bar is now centered within the available space in the same way as the main content. Its `width: 100%` and `max-width: 500px` ensure its size perfectly mirrors the `.dashboard-container` above it at all screen sizes.
* **Removes Inconsistency:** This eliminates the problem where the navigation bar could be slightly wider or narrower than the content.

### **Important Note on Reactivity**

This CSS-only change will fix the width and alignment. However, due to the fundamental nature of `position: fixed` (which always relates to the browser viewport), the bar will **still not shift horizontally** when the Home Assistant sidebar is opened. Solving that specific issue requires complex JavaScript to listen for sidebar changes and dynamically adjust the bar's position, which is a much larger task. This fix addresses the core alignment problem cleanly and effectively.

Separately. Can you increase the icon size to the same value as is the case for the header button icons
