### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by mholzi** [mholzi/dashview#95]
Of course. To align the navigation bar icons with the header icons, we should make all of them a consistent size. The most common and prominent size used is `24px`. The floor and room icons in the header are slightly smaller at `22px`.

Here is a full prompt with step-by-step instructions to modify the CSS and make all interactive icons a uniform `24px`.

### Objective

Update the stylesheet to set the `font-size` of the floor and room header icons to `24px`, aligning them with the icons in the bottom navigation bar and the main kiosk header button.

### Step 1: Locate the CSS File

Open the following file in your editor:
`custom_components/dashview/www/style.css`

### Step 2: Find the Target CSS Rule

Inside the `style.css` file, search for the selector that styles the floor and room header icons. The selector is:
`.header-floor-button i, .header-room-button i`

You will find the following CSS rule:

```css
.header-floor-button i,
.header-room-button i {
    font-size: 22px;
    width: 22px;
    height: 22px;
    display: flex;
    justify-content: center;
    align-items: center;
}
```

### Step 3: Modify the CSS Rule

Change the `font-size`, `width`, and `height` properties from `22px` to `24px`. This will increase the size of the floor and room icons to match the navigation bar icons.

**Change the code from this:**
```css
/* ... Previous code ... */
.header-floor-button i,
.header-room-button i {
    font-size: 22px;
    width: 22px;
    height: 22px;
    display: flex;
    justify-content: center;
    align-items: center;
}
/* ... Following code ... */
```

**To this:**
```css
/* ... Previous code ... */
.header-floor-button i,
.header-room-button i {
    font-size: 24px;
    width: 24px;
    height: 24px;
    display: flex;
    justify-content: center;
    align-items: center;
}
/* ... Following code ... */
```

### Step 4: Save and Refresh

Save the `style.css` file. You will likely need to clear your browser's cache and reload the Home Assistant page to see the changes take effect.

After completing these steps, the floor and room icons in the header will be `24px`, matching the size of the icons in the bottom navigation bar and creating a fully aligned and consistent look across your interface.
